import axios from 'axios'
import Head from 'next/head'
import 'primeicons/primeicons.css'
import { Dropdown } from 'primereact/dropdown'
import { FileUpload } from 'primereact/fileupload'
import { InputText } from 'primereact/inputtext'
import 'primereact/resources/primereact.min.css'
import 'primereact/resources/themes/lara-light-indigo/theme.css'
import { useRef, useState } from 'react'

export default function Admin() {
  const collegeSelectItems = [
    { label: 'DTU', value: 'DTU' },
    { label: 'NSUT', value: 'NSUT' },
    { label: 'IGDTUW', value: 'IGDTUW' },
  ]

  const yearSelectItems = [
    { label: 'First', value: 'first' },
    { label: 'Second', value: 'second' },
  ]

  const subjectSelectItems = [
    { label: 'Maths', value: 'maths' },
    { label: 'Physics', value: 'physics' },
    { label: 'Chemistry', value: 'chemistry' },
    { label: 'Computer', value: 'computer' },
  ]

  const topicSelectItems = [
    { label: 'Book', value: 'book' },
    { label: 'Assignment', value: 'assignment' },
    { label: 'Paper', value: 'paper' },
    { label: 'Playlist', value: 'playlist' },
    { label: 'Experiment', value: 'experiment' },
    { label: 'Notes', value: 'notes' },
  ]

  const [formData, setFormData] = useState({
    college: collegeSelectItems[0],
    year: yearSelectItems[0],
    subject: subjectSelectItems[0],
    topic: topicSelectItems[0],
    name: '',
  })

  const [files, setFiles] = useState<File[]>([])
  const input_ref = useRef<HTMLInputElement>(null)

  const uploadHandler = async (event: any) => {
    for (let i = 0; i < files.length; i++) {
      console.log(files[i])
      let uploadData = new FormData()
      uploadData.append(files[i].name, files[i])
      for (let pair of uploadData.entries()) {
        console.log(pair[0] + ', ' + pair[1])
      }
      let { data } = await axios.post('/api/upload', {
        name: files[i].name,
        type: files[i].type,
        files: {
          demo: JSON.stringify(uploadData),
        },
      })
      console.log(data)
    }
  }

  const handleChange = async (event: any) => {
    let fileArray: File[] = []
    for (let i = 0; i < event.target.files.length; i++) {
      fileArray.push(event.target.files[i])
      const Form = new FormData()
      Form.append('file', event.target.files[i])
      console.log(Form)
    }
    setFiles((prev) => {
      return [...prev, ...fileArray]
    })
  }

  const chooseHandler = (event: any) => {
    input_ref.current?.click()
  }

  return (
    <div>
      <Head>
        <title>Movie Titles</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Dropdown
        value={formData.college}
        options={collegeSelectItems}
        onChange={(e) =>
          setFormData((prev) => {
            return { ...prev, college: e.value }
          })
        }
        placeholder='Select a College'
      />
      <Dropdown
        value={formData.year}
        options={yearSelectItems}
        onChange={(e) =>
          setFormData((prev) => {
            return { ...prev, year: e.value }
          })
        }
        placeholder='Select a Year'
      />
      <Dropdown
        value={formData.subject}
        options={subjectSelectItems}
        onChange={(e) =>
          setFormData((prev) => {
            return { ...prev, subject: e.value }
          })
        }
        placeholder='Select a Subject'
      />
      <Dropdown
        value={formData.topic}
        options={topicSelectItems}
        onChange={(e) =>
          setFormData((prev) => {
            return { ...prev, topic: e.value }
          })
        }
        placeholder='Select a Topic'
      />
      <InputText
        value={formData.name}
        onChange={(e) =>
          setFormData((prev) => {
            return { ...prev, name: e.target.value }
          })
        }
      />

      <FileUpload
        name='demo'
        uploadHandler={uploadHandler}
        url='/api/upload'
        multiple
      />
      <input
        type={'file'}
        multiple
        onChange={handleChange}
        ref={input_ref}
        className='hidden'
      />
      <div className='flex gap-2'>
        <div
          onClick={chooseHandler}
          className='bg-blue-500 text-white text-2xl font-bold w-fit py-2 px-6 rounded-lg cursor-pointer'
        >
          Choose
        </div>
        <div
          onClick={uploadHandler}
          className='bg-blue-300 text-white text-2xl font-bold w-fit py-2 px-6 rounded-lg cursor-pointer'
        >
          Upload
        </div>
        <div
          onClick={() => setFiles([])}
          className='bg-blue-300 text-white text-2xl font-bold w-fit py-2 px-6 rounded-lg cursor-pointer'
        >
          Cancel
        </div>
      </div>
      <div className=' flex flex-col gap-2 mt-4'>
        {files
          .map((file, idx) => {
            return (
              <div
                key={idx}
                className='py-4 px-2 rounded-lg bg-slate-900 w-1/2 text-white text-center'
              >
                {file.name}
              </div>
            )
          })
          .reverse()}
      </div>
    </div>
  )
}
